services:
  container:
    image: <TBD>
    container_name: <TBD>
    hostname: <TBD>
    environment:
      DISPLAY: :0
      QT_X11_NO_MITSHM: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - <Bind mount to container src>
    tmpfs:
      - /tmp
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
